resolve issue17
04-Management-of-SD/web pull request #25
Opened 2021-11-17 02:42 UTC by sptungG

**Input**: #17

**Ouput**: Room page

**Process**: 

Desing UI

fetch data sampple

2021-11-17 03:38 UTC, huythangphan requested changes
1. Remove package-lock, yarn.lock ra khỏi PR
2. PR desc: Screenshot cần để ở Output thay vì Process

2021-11-17 03:38 UTC, huythangphan commented on src/based/Common.js
>  				break;
thêm case 'postdate' thay vì replace 'jsondate'

2021-11-17 03:38 UTC, huythangphan commented on src/based/Common.js
> +	formatPrice1: (price) => new Intl.NumberFormat('vi-VN', { maximumSignificantDigits: 3 }).format(price)
sao phải thêm mới formatPrice1 thế

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/RoomsListing.js
> +// import { ArrayToKeyValueFormData, ObjectToKeyValueFormData } from '../based/ProcessData'
nếu ko sử dụng thì nên remove thay vì comment lại

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/RoomsListing.js
> +  // }
remove

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/RoomsListing.js
> +  // }
nếu ko sử dụng thì nên remove thay vì comment lại

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/RoomsListing.js
> +                width="170px"
ở <th> đã set width nên ở đây ko cần set nữa

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/RoomsListing.js
> +              item?.type?.priceUnit
tạo biến ở loop phía trên rồi đặt ở đây. ví dụ `pricePerUnit`

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/components/RoomEditor.js
> +// import { initRoom } from '../../based/InitializeData'
remove

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/components/RoomEditor.js
> +// import CommonSelect from '../../based/inputs/CommonSelect'
remove

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/components/RoomEditor.js
> +// ]
remove

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/components/RoomEditor.js
> +  // }
remove

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/components/RoomEditor.js
> +  // }
remove

2021-11-17 03:38 UTC, huythangphan commented on src/manage-room/components/RoomEditor.js
> +                    name="slot"
available_slot?

2021-11-17 08:17 UTC, sptungG commented on src/based/Common.js
> +	formatPrice1: (price) => new Intl.NumberFormat('vi-VN', { maximumSignificantDigits: 3 }).format(price)
cái formatPrice ở trên nó thành 10.000đ ko bt chuyển kiểu gì :<<

2021-11-18 06:20 UTC, huythangphan requested changes
Ko xóa file package-lock và yarn.lock mà giữ nguyên content file ở main

2021-11-18 06:20 UTC, huythangphan commented on .gitignore
> +yarn.lock
chỉ cần ignore yarn.lock

2021-11-18 06:20 UTC, huythangphan commented on src/based/Breadcumbs.js
> +/* eslint-disable */
sao lại disable ở đây

2021-11-18 06:20 UTC, huythangphan commented on src/based/Common.js
> +		if (date == null || date === 'Invalid Date') return '';
`date === null` chứ

2021-11-18 06:20 UTC, huythangphan commented on src/based/Common.js
> +		// eslint-disable-next-line default-case
ko disable ở đây. thêm default case

2021-11-18 06:20 UTC, huythangphan commented on src/based/Common.js
> +	formatPrice1: (price) => new Intl.NumberFormat('vi-VN', { maximumSignificantDigits: 3  }).format(price)
modify formatPrice để tránh lặp code

2021-11-18 06:20 UTC, huythangphan commented on src/based/Common.js
>  				break;
chưa resolve comment này

2021-11-18 06:20 UTC, huythangphan commented on src/manage-room/RoomsListing.js
> +                width={150}
header <th> đã có width nên <td> ko cần nữa

2021-11-18 06:20 UTC, huythangphan commented on src/manage-room/RoomsListing.js
> +              item?.type?.priceUnit
chưa resolve comment ở đây

2021-11-18 08:38 UTC, sptungG commented on src/based/Common.js
> +		if (date == null || date === 'Invalid Date') return '';
date == null tương đương với date === undefined || date == null

2021-11-18 12:44 UTC, huythangphan commented on src/based/Common.js
> +		if (date == null || date === 'Invalid Date') return '';
nếu muốn check 2 case `undefined` và `null` thì có thể dùng `!date` còn ko thì phải nêu rõ ra đang check `undefined` hay `null`

2022-01-04 14:35 UTC, merged